server:
  port: ${BPD_POINT_PROCESSOR_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

point-processor:
  mcc-score-multiplier: {
    "internal": "0.0"
  }

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.bpd.point_processor: ${LOG_LEVEL_BPD_POINT_PROCESSOR:DEBUG}