apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmspointprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmspointprocessor
  template:
    metadata:
      labels:
        app: bpdmspointprocessor
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmspointprocessor
          image: cstarprodregistry.azurecr.io/bpdmspointprocessor
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: bpdmspointprocessor
            - configMapRef:
                name: bpdmspointprocessor
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: jvm
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4