apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmspointprocessor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bpdmspointprocessor
  template:
    metadata:
      labels:
        app: bpdmspointprocessor
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmspointprocessor
          image: cstarprodregistry.azurecr.io/bpdmspointprocessor
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: bpdmspointprocessor
            - configMapRef:
                name: bpdmspointprocessor
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4