apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpdmspointprocessor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmspointprocessor
    spec:
      containers:
        - name: bpdmspointprocessor
          image: cstarregistry.azurecr.io/bpdmspointprocessor-uat
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: bpdmspointprocessor
            - configMapRef:
                name: bpdmspointprocessor
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: rest-client
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.10